name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - name: Install wasm-bindgen-cli
        run: cargo install -f wasm-bindgen-cli --version 0.2.104

      - run: rustup target add wasm32-unknown-unknown

      - name: Build wasm
        run: |
          cargo build --target wasm32-unknown-unknown


      - name: bindgen
        run: |
          wasm-bindgen ./target/wasm32-unknown-unknown/debug/rust-wasm-bindgen-testbed.wasm \
            --out-dir ./bindgen-wasm-testbed/wasm/ \
            --target bundler

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: cd ./bindgen-wasm-testbed

      - run: pnpm i

      - run: pnpm build
